version: '3'

services:
  postgresql:
    image: postgres:16rc1
    environment:
      POSTGRES_USER: joanix
      POSTGRES_PASSWORD: E3VVws6nCb08Vr77
      POSTGRES_DB: video-gen-base
    networks:
      - VideoGenNet
      
  django:
    image: vgapi
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - VideoGenNet
      
networks:
  VideoGenNet:
