# Generated by Django 4.1 on 2023-09-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
